HCF-1167 make lint/format should fail on error
When the program (golint / goimports) reports an error — for example
because they were not installed - we should correctly fail.

This fixes the issue by getting rid of the pipe so `errexit` is still in
effect.  While we're there, get rid of the `wc` too, since we can just
test for an empty file.  That means always removing the file during the
trap, rather than early, which lets us unconditionally cat it too.

Also fixes problems identified by shellcheck.

diff --git a/make/format b/make/format
--- a/make/format
+++ b/make/format
@@ -4,20 +4,16 @@ set -o errexit
 
 . make/include/colors.sh
 
-echo "${OK_COLOR}==> Formating ${ERROR_COLOR}"
-ISSUES=$(mktemp /tmp/XXXXX)
+printf "%b==> Formatting %b\n" "${OK_COLOR}" "${ERROR_COLOR}"
 
-trap "rm -f ${ISSUES}" HUP INT TERM
+ISSUES=$(mktemp)
+
+trap "cat ${ISSUES} ; rm -f ${ISSUES}" EXIT
 
 go list -f '{{ .Dir }}' ./... | grep -v /vendor/ | while read DIR; do
-    goimports -d -e ${DIR}/*.go | tee -a ${ISSUES}
+    goimports -d -e "${DIR}"/*.go >> "${ISSUES}"
 done
 
-ISSUE_COUNT=$(cat ${ISSUES} | wc -l)
+printf "%b" "${NO_COLOR}"
 
-rm -f ${ISSUES}
-
-echo "${NO_COLOR}\c"
-
-test ${ISSUE_COUNT} -eq 0
-
+test ! -s "${ISSUES}"
